### ISSUE TITLE
Build Status missing

### ISSUE THREAD

**Issue by rgbm21** [jlord/git-it-electron#108]
![git-it](https://cloud.githubusercontent.com/assets/6115991/13387251/7fedf44c-debd-11e5-94b2-ca29d1b764fa.png)

- It's not redirected to proper build status link, it redirects to https://travis-ci.org/maxogden/electron-packager :smile:

**Comment by jlord** [comment]
lol, whoops, thanks :+1:

**Comment by rgbm21** [comment]
:v: cool
