### ISSUE TITLE
Mac install step-by-step

### ISSUE THREAD

**Issue by wilsonmar** [jlord/git-it-electron#121]
Since the audience of this repo can be newbies, I think it would help to provide step-by-step instructions on how to download and install this wonderful app. For example:

0. Use an internet browser to go to the Releases section at https://github.com/jlord/git-it-electron/releases
0. If you're using a Mac OSX, click on **Git-it-darwin-x64.zip** to download it to your **Downloads** folder.
0. Watch for the file to finish downloading. The Safari browser sends the file to the bottom:
   <img width="460" alt="git-it download" src="https://cloud.githubusercontent.com/assets/300046/14673207/c05a59c0-06b9-11e6-9af1-76d44c40b895.png">

   The Firefox browser shows downloads with an arrow icon:
   <img width="440" alt="git-it download on firefox" src="https://cloud.githubusercontent.com/assets/300046/14673795/48b289a2-06bd-11e6-906e-7d0c1440565f.png">

0. Unzip the file by double-clicking on the zip file.
0. In Finder, navigate into the **Git-it-darwin-x64** folder.
0. Click Finder menu File, New Finder window.
0. In that new window, click menu Go, then Applications.
0. Drag **Git-it** and drop it into the Applications files.
0. Hold down the **control** key on your keyboard and click **Git-it** for the context menu:

   ![git-it open](https://cloud.githubusercontent.com/assets/300046/14673485/6b72f956-06bb-11e6-994d-954b36803004.jpg)

0. Click Open.
0. Click Open to confirm the warning:

   ![mac osx app from another](https://cloud.githubusercontent.com/assets/300046/14673676/858ba99a-06bc-11e6-9daa-ea42076b6bd5.jpg)

0. The Git-it welcome screen should appear:

   <img width="786" alt="screen shot 2016-04-20 at 6 03 08 am" src="https://cloud.githubusercontent.com/assets/300046/14673853/a7a583d8-06bd-11e6-8fd7-24e4c6500f0d.png">

0. In Finder delete the downloaded zip file.

I don't know if the above is what you intended to occur, but that's what I did to install it, anyway.

**Comment by jlord** [comment]
Thanks for this thoughtful issue @wilsonmar, I definitely want to make installing and getting going clear and issue.

The thing is that I've not officially released this yet, which is why it's not complete :D 

I will be releasing soon though and will make sure to cover this 👍

**Comment by gonsie** [comment]
Just a heads up since the Git-it app is not signed, users will need to enter an administrator password to successfully run it.

**Comment by magistr011** [comment]
Russian localization does not work
