### ISSUE TITLE
git-it release version(4.1.0) for Mac make blank screen for "Pull Never Out of Date"

### ISSUE THREAD

**Issue by fu7mu4** [jlord/git-it-electron#126]
I'm using git-it electron release version 4.1.0 on Mac , 
but on one of challenge : "Pull Never Out of Date" , git-it make blank screen. 
In this situation, I cannot operate this app so I have to kill this app.
On other challenges, this make good screen.  no problem.

**Comment by willslone** [comment]
I had the same problem. I dug into the apps package contents and found the following files missing:

app/challenges/pull_never_out_of_date.html
app/challenges-ja/pull_never_out_of_date.html
app/challenges-zhtw/pull_never_out_of_date.html

app/challenge-content/9_pull_never_out_of_date.html
app/challenge-content-ja/9_pull_never_out_of_date.html
app/challenge-content-zhtw/9_pull_never_out_of_date.html

app/lib/verify/pull_never_out_of_date.js

Copying these files from the repo and placing them in their respective folders fixed the issue.

**Comment by jlord** [comment]
Weird, I wonder if the release somehow did not get updated. Can you try again and re-download the Mac version 4.1.0? I've replaced the .zip and it seems to be working on my end.

**Comment by willslone** [comment]
That fixed it for me.

**Comment by fu7mu4** [comment]
That fixed if for me, too. thanks a lot.
