### ISSUE TITLE
no icon

### ISSUE THREAD

**Issue by strongant** [jlord/git-it-electron#140]
when app start, it have no icon.[
![tes png](https://cloud.githubusercontent.com/assets/7685936/15996732/c7c2dba0-315d-11e6-8af0-019c54c9b2b0.png)
](url)

**Comment by strongant** [comment]
how to resolve it?

**Comment by jlord** [comment]
Hmm, I believe I tested it on Ubuntu 14.04 and had the icon working. I'll look into it again.

**Comment by strongant** [comment]
Ubuntu 14.04,i already resolve this problem that create a .desktop .
