### ISSUE TITLE
Use a different repository name than "hello-world"

### ISSUE THREAD

**Issue by restartedwill** [jlord/git-it-electron#142]
If someone is brand new to git, github's getting started suggested task is to make a "hello-world" repository. But git-it uses the same name for its repository. We should use some other name for git-it. I spent a great deal of time trying to deal with an existing repository with a file already created before starting using git-it, ultimately blowing away the getting started's hello-world repository and then starting over with git-it.

**Comment by jlord** [comment]
Thanks for the feedback. This could be an issue for all kinds of projects since 'hello-world' is the canonical starter name. I'm hesitant to change it right now but I'll add text to suggest they name it something else if they already have something called 'hello-world'.
