### ISSUE TITLE
Git it Remote Control page

### ISSUE THREAD

**Issue by awgregory** [jlord/git-it-electron#143]
Dear Jlord,  I'm working through Git it and have Github Desktop on my Windows 10 Computer.  I found that a remote named 'origin' was not automatically created in my local repo as described in the tutorial.  Has something changed?  Also is there a command to list remotes that have been previously created?    Thanks

> Windows Users:

> If you have GitHub Desktop on your computer, a remote named 'origin' is automatically created in your local repository. In that case, you'll just need to tell it what URL to associate with 'origin'. Use this command instead of the 'add' one above:

> git remote set-url origin <URLFROMGITHUB>

**Comment by jlord** [comment]
Interesting. Perhaps this has been changed. If you don't already have `origin` than you can proceed with the instructions and ignore that part.

To see the remotes that exist in the repository you can type: 

```bash
git remote -v
```
