### ISSUE TITLE
Same tutorial in GIFS

### ISSUE THREAD

**Issue by khaledMohammed000** [jlord/git-it-electron#148]
Hello, is it okay if i share the same tutorials for learnign GIT in GIF format , as that would be a great addition .. apart from having Images

GIF for every command

**Comment by jlord** [comment]
Hi!

I'm not sure what you mean here, you want to use screenshots from the app and turn them into gifs? I think regardless of format, if you want to use the content from here you're free to do so according to the [license](https://github.com/jlord/git-it-electron/blob/master/LICENSE). Thanks for checking!
