### ISSUE TITLE
GitHubbin hangs on verification

### ISSUE THREAD

**Issue by ShipsWithCannons** [jlord/git-it-electron#161]
GitHubbin hangs on the verification. Won't complete. Trying again had no effect.

Git version 2.7.4.
Git-it version 4.2.0.
Ubuntu 16.04 LTS x64.

**Comment by g8rengr** [comment]
having same issue...
Git Version 2.10.0.windows.1
Git-it version 1.6.9
windows 7 Pro x64

**Comment by isonet** [comment]
Duplicate: #160

**Comment by jlord** [comment]
I've added a new version that has the missing dependency (don't know why it was't bundled to begin with...) here: https://github.com/jlord/git-it-electron/releases/tag/4.2.2
