### ISSUE TITLE
Unable to verify username 

### ISSUE THREAD

**Issue by An3bi** [jlord/git-it-electron#166]
I am unable to have my username be verified on the Fourth challenge. 
 I used 
`$ git config --global user.username An3bi`

However, after clicking _verify_, it keeps loading 

I have been unable to debug the issue.
Is there an apparent issue with the way I wrote it?

**Comment by w3code** [comment]
Same issue on my Mac  

###### Macbook Air with Mac OS Sierra

**Comment by jlord** [comment]
I've added a new version that fixes the missing dependency which was causing this error (dupe of issue #160) here: https://github.com/jlord/git-it-electron/releases/tag/4.2.2 🍍
