### ISSUE TITLE
css ::before  blocks translate  of other language

### ISSUE THREAD

**Issue by fuchao2012** [jlord/git-it-electron#172]
In file : new-challenge.css

```
.chal-no-pass.border-box::before {
  content: "Didn't Pass?";
}

.chal-tip.border-box::before {
  content: "Tips";
}

.chal-step.border-box::before {
  content: "Step";
}

.chal-goal.border-box::before {
  content: "Goal";
}
```

btw, I am translating git-it into simple-chinese,  and `content` in the `css files` blocks the translate.

According to this [demo](http://jsfiddle.net/p4jDn/4/).

May this can help 

```
div::before {
    content: attr(data-content);
  }
```
and use javascript to change content in css, while changing the language.

```
 $(this).attr('data-content','提示');
```

**Comment by jlord** [comment]
> I am translating git-it into simple-chines

Kewl!

Would you mind showing some screenshots of what you're trying to do and where the problem is? Is it impacting the current Traditional Chinese and Japanese translations?

**Comment by jlord** [comment]
Closing for now because stale. Feel free to re-open with updates! ✨
