### ISSUE TITLE
What Next and Ideas for Beginner Projects hyperlinks lead to blank page

### ISSUE THREAD

**Issue by seraries** [jlord/git-it-electron#188]
I downloaded the New Year's release for Windows and worked through it. It's awesome, thanks so much! But a couple issues with links leading only to blank pages: 1. On the last page/last chapter, the What Next hyperlink leads to a blank page, 2. On the home page once all chapters are completed, the Ideas for Beginner Projects hyperlink also leads to a blank page.

**Comment by jlord** [comment]
Oh interesting. Thanks for reporting this! I'll look into it when I get the chance.

**Comment by jlord** [comment]
Fixed in #208 ✨
