### ISSUE TITLE
Provide a screenshot in the README

### ISSUE THREAD

**Issue by steelbrain** [jlord/git-it-electron#19]
Just like the title says.

**Comment by IonicaBizau** [comment]
@steelbrain I have just opened a PR for this. :smile:

**Comment by jlord** [comment]
Same as comment to #21—would rather not have something up right now that will likely be out of date soon or provide people the false belief that this actually works right now, haha. But later on, yes, definitely! Along with a whole other, proper readme :smile:

**Comment by IonicaBizau** [comment]
@jlord We could make an `npm` script in `package.json` to generate and update the screenshot in the readme file. :smile:

But I've got it. It makes sense. :+1:

**Comment by jlord** [comment]
:ship:
