### ISSUE TITLE
Can't DONE!

### ISSUE THREAD

**Issue by hotuta** [jlord/git-it-electron#192]
I can't DONE git-it-electron.

![2017-05-09 20 28 02](https://cloud.githubusercontent.com/assets/11851747/25848620/158a0a38-34f6-11e7-9148-9f776922f2f5.png)

I clicked "DONE!".

![2017-05-09 20 28 55](https://cloud.githubusercontent.com/assets/11851747/25848627/24527eec-34f6-11e7-9e06-329dde6c4b4a.png)

I'm on mac.

**Comment by floridop** [comment]
Same here on Ubuntu 14.04 amd64

**Comment by jlord** [comment]
Thanks! There was an incorrect file path being used, I just fixed it in #208 and it will be in the next release ✨
