### ISSUE TITLE
could you tell me how to run your source code ?

### ISSUE THREAD

**Issue by Carbs0126** [jlord/git-it-electron#198]
i use "electron .", but just show a blank window, could you tell me how to run your source code ?

**Comment by jlord** [comment]
Hi!

Do you have Node installed on your computer? Have you seen this section for running it locally?

https://github.com/jlord/git-it-electron/blob/master/CONTRIBUTING.md#building-locally

**Comment by Carbs0126** [comment]
thank you so much for your answer! 
now could i ask you another question?
Is electron able to setup a suspension window? such as a little square window on top of all windows to show downloading progress. usually used by some download software

**Comment by jlord** [comment]
Yep, you could do that with Electron. 

Since this isn't a question about git-it in particular, I'll close this issue. Good luck!
