### ISSUE TITLE
Specify user{Data, Cache} directories

### ISSUE THREAD

**Issue by steelbrain** [jlord/git-it-electron#20]
Currently You have not specified userData and userCache directories in the browser (main) process. Which means that default `Electron Default App` dirs are used.
Example: https://github.com/steelbrain/Brauser/blob/master/Browser/Main.js#L17

**Comment by jlord** [comment]
Yep! This is because I'm just doing an initial wiring up of things and am not worried it being in the right spot at this time. But yes, I will be putting it in the app path eventually.

**Comment by jlord** [comment]
Closed via https://github.com/jlord/git-it-electron/pull/41
