### ISSUE TITLE
Current live/installable mac version missing resources.html

### ISSUE THREAD

**Issue by gnovakov** [jlord/git-it-electron#200]
Hi, the Current live/installable mac version missing resources.html file in :

/Applications/Git-it.app/Contents/Resources/app/built/en-US/pages/

it only has the about.html, the dictionary.html and the index.html.

Your latest git-it-electron master branch does seem to have these pages though:

https://github.com/jlord/git-it-electron/blob/master/resources/contents/en-US/pages/resources.html

I fixed it personally for myself by downloading the latest resources.html and putting it in the pages/resources.html manually, but other people might find issues as well. :-)

**Comment by jlord** [comment]
Fixed in #208 ✨
