### ISSUE TITLE
My last step error: No merge in the history

### ISSUE THREAD

**Issue by dagadbm** [jlord/git-it-electron#201]
Seems like I can't complete the last step:
![image](https://user-images.githubusercontent.com/16737095/28495407-a852bef0-6f43-11e7-84bb-45afc15feaef.png)

I did things a little bit differently I'm afraid. What exactly am I missing?

Also, when I click on the Whats Next link the app just goes blank and doesn't respond.

Awesome work btw, finally I understand a bit better how git works!

**Comment by jlord** [comment]
Hi!

> Also, when I click on the Whats Next link the app just goes blank and doesn't respond.

I have just fixed that bug and the fix will be in the next release 😅 

> I did things a little bit differently I'm afraid. What exactly am I missing?

How so? Did you merge your branch into the `master` branch?
