### ISSUE TITLE
Wrong folder expected in "Branches Aren't for Birds"

### ISSUE THREAD

**Issue by vsingh0075** [jlord/git-it-electron#211]
During verification in this stage, app expects the folder to be named as "contributors", while in the repository it has a "C" in upper case. Please fix soon! 
`Error: ENOENT: no such file or directory, scandir '/home/vikrant/Development/patchwork/contributors/'`

**Comment by Undigon** [comment]
I had this issue too. I mv'd the whole folder to lower case contributors which helped in the short term but later repobot wouldn't accept my pull request.

**Comment by jlord** [comment]
The folder in the Patchwork repo was mistakenly re-created with an uppercase 'C' 😢 (sorry!) and I've corrected that now: https://github.com/jlord/patchwork/commit/8aa3ae91c6bb038bd9053c00c0a9ca3acc8a796b
