### ISSUE TITLE
Uncaught Exception: Error: Cannot find module 'shell'

### ISSUE THREAD

**Issue by JonHodgins** [jlord/git-it-electron#221]
![error](https://user-images.githubusercontent.com/19355502/37811714-0d48955c-2e19-11e8-85a6-8efb71a8104d.PNG)

Error thrown upon clicking Help > Repository 

Also stuck on trying to verify the git directory. I assume these issues are related. 

![stuckverify](https://user-images.githubusercontent.com/19355502/37811713-0d320d8c-2e19-11e8-9948-b5916650d22d.PNG)

**Comment by JonHodgins** [comment]
Checked console. This is error thrown upon clicking Verify

![console](https://user-images.githubusercontent.com/19355502/37811947-501ab7e2-2e1a-11e8-82b3-fbcb12f47b56.PNG)

**Comment by jlord** [comment]
Fixed with https://github.com/jlord/git-it-electron/pull/220 🎉
