### ISSUE TITLE
How to open Git Shell?

### ISSUE THREAD

**Issue by Owleen** [jlord/git-it-electron#245]
In the first challenge, "Get Git", it says: "Once GitHub Desktop (and therefore Git) is installed, open your terminal". I've downloaded and set up GitHub Desktop on my Windows, but I don't know how to access the terminal. Also, above that instruction, it says "Windows: Use the Git Shell for your terminal.".

**Comment by jotoeri** [comment]
Hi Owleen,

I don't know if this topic solved for you already, but you're right, I had the same issues. It seems like the GitHub Desktop App maybe provided the Git installation once the Git-It Project was started. Now, Git seems to be implemented into the GitHub Desktop-App such that its not necessary to install Git on the whole system.

I solved this problem by installing Git manually, which was also the suggestion of the GitHub Desktop-App when clicking on Repository / 'Open in Command Prompt'. You can get Git here:
https://git-scm.com/download/win

Once you have installed it, you can (after reboot) use the Windows Terminal (cmd) for Git-It or use the Git Bash, which should have been installed with the above mentioned Git-Installlation.

Finally, maybe the first Task of Git-it should be updated such, that you have to install Git separately (or exclusively for Git-it)

Greetings!
Jonas

**Comment by Owleen** [comment]
Hi Jonas,

Thank you for your answer! I downloaded Git separately and now I'm able to work through the Git-It modules on Git Bash. 

Thanks again
