### ISSUE TITLE
branches aren't just for birds

### ISSUE THREAD

**Issue by vdloc** [jlord/git-it-electron#251]
I found a typo mistake in the first "Step" section in "Branches Aren't Just For Birds" lesson. 
> While still inside of your local 'patchwork' repository, type git status to see what branch you're currently on. Git should reply that you're on the 'gh-pages' branch.

so instead type 'git status' we have to type 'git branch'.
Please ignore this issue if you think it's not necessary.

**Comment by jotoeri** [comment]
Shouldn't be a typo, no...? Git gives you a very nice and more intuitive feedback by 'git status':

On branch gh-pages
Your branch is up to date with 'origin/gh-pages'

**Comment by vdloc** [comment]
> 
> 
> Shouldn't be a typo, no...? Git gives you a very nice and more intuitive feedback by 'git status':
> 
> On branch gh-pages
> Your branch is up to date with 'origin/gh-pages'

oh I sorry, It's my mistake because had used an alias for git status -s so it didn't show the branch info.
Please close this issue!

**Comment by jlord** [comment]
Thanks @jotoeri!
