### ISSUE TITLE
Un-intuitive Capitalization

### ISSUE THREAD

**Issue by 0x15F9** [jlord/git-it-electron#253]
I think this might have been left out intentionally to reflect the *capitalize where capitalized* part but, in my opinion, it does properly serve its purpose and seems like a  typo.
As a solution, I propose that it is mentioned in the challenge that the username is *UserName*
![ScreenShot](https://user-images.githubusercontent.com/17203172/52900252-251afc80-320d-11e9-8e3d-f3a8d9ffc3e2.png)

**Comment by jlord** [comment]
Fixed with #252. Thanks!
