### ISSUE TITLE
How do i complete the 1st challenge ? How to integrate git-it with terminal and code editor?

### ISSUE THREAD

**Issue by AishPN** [jlord/git-it-electron#298]
![image](https://user-images.githubusercontent.com/48025239/87778797-5efc9200-c849-11ea-84d2-368ab2348ca7.png)
What do i do now? Please help!

**Comment by jotoeri** [comment]
Hey Aishwarya,

seems like you are running on mac? I'm not experienced at all with mac, but from a short search on google, you could maybe try reinstalling xcode...? -> [Thread on stackoverflow](https://stackoverflow.com/questions/58308715/missing-xcrun-at-library-developer-commandlinetools-usr-bin-xcrun-failed-to-cl)

Hope that helps,
Greets,
Jonas

**Comment by AishPN** [comment]
Thanks a lot! It worked.
