### ISSUE TITLE
fetch --dry-run error: cannot spawn C:\Windows\System32\OpenSSH\ssh.exe: No such file or directory fatal: unable to fork

### ISSUE THREAD

**Issue by ProcrastinatingEntrepreneur** [jlord/git-it-electron#303]
# On the Pull Never out of Date problem when clicking verify it spits out this to the log. 
Error: Command failed: "C:\Users\userName\Desktop\Git-it-Win-ia32\resources\app\assets\PortableGit\bin\git.exe " fetch --dry-run error: cannot spawn C:\Windows\System32\OpenSSH\ssh.exe: No such file or directory fatal: unable to fork

**Comment by jotoeri** [comment]
Hm - two things:
- Did you clone via ssh? -> So what is the output of your `git remote -v`?
- Do you have OpenSSH installed on Windows? (You can check this via Settings->Apps->Optional Features-> OpenSSH-Client should exist)

Greets :)
Jonas

**Comment by ProcrastinatingEntrepreneur** [comment]
Yes I cloned it with SSH and yes I have open SSH installed and it's in that
directory that it's looking for but for some reason it doesn't detect it

**Comment by jotoeri** [comment]
To be honest, i cant reproduce it currently. Seems to me a bit like some rights-related stuff.
However, Git-it uses a bundled portableGit here, which cannot access your SSH-Stuff anyways like your own installed console. So if Git-it could access your ssh.exe you will still get an Error of a missing access to your key, as you are not able to enter your keys password within Git-it's Verify-Process (even ssh-agent does not help).
As dumb as it sounds - I'd say Git-it is just not made here to use ssh, but to use https, as it is described in the challenge. Changing your remote to https should enable you to verify the challenges and if you're able to use the ssh-setup on your daily work from your console, then you're all good?! 🤔
