### ISSUE TITLE
Ship with Git English Language Pack?

### ISSUE THREAD

**Issue by jlord** [jlord/git-it-electron#43]
For Git-it to work no matter what language people use with Git on their computer, Git-it needs to switch the lang to English when it runs. I think this works sometimes, but it doesn't if the user does't have the language pack on their system.

I really don't know what I'm talking about with this, anyone have any ideas?

What can we add to the app so that this always works:

```javascript
process.env.LANG = 'en_US.UTF-8'
```

**Comment by IonicaBizau** [comment]
> For Git-it to work no matter what language people use, Git-it needs to switch the lang to English when it runs. 

Could I ask why? :smile:

**Comment by jlord** [comment]
@IonicaBizau because Git-it is trying to match strings from Git output. So it's expecting "on branch master" when, if you're using another language, it will see something like "Auf Branch master" and fail the challenge even though you've passed. See https://github.com/jlord/git-it/issues/185.

Thought it had been fixed with https://github.com/jlord/git-it/pull/149 by setting the `env.LANG` to English, but seems some systems may not have this file. So wondering if it's something that can be bundled with Git-it.

**Comment by jlord** [comment]
> To change all locale settings, use LANG=C. The locale as used in C is English and always available without installing additional language packs.

—http://askubuntu.com/questions/142812/temporarily-change-language-for-terminal-messages-warnings-errors/142814#142814

**Comment by IonicaBizau** [comment]
Got it! But what about [trying to use the natvie Node bindings to the libgit2 project.](https://github.com/nodegit/nodegit)?

**Comment by jlord** [comment]
Gonna go with https://github.com/jlord/git-it-electron/commit/a4759e2350c0da8ca89a354597fca2bc95f97891 for now.
