### ISSUE TITLE
Other Things To Do

### ISSUE THREAD

**Issue by jlord** [jlord/git-it-electron#50]
Not critical, but would be :sparkles: 

- [x] Remember directories https://github.com/jlord/git-it-electron/issues/47
- [ ] TESTS (Ok, pretty critical)
- [x] Refactor HTML & scripts for verify buttons. #55 
- [ ] Separate concerns correctly between `helper.js` and `challenge-completed.js`
- [x] Have the 'Get Started' button change to a 'Finish Where I Left Off' button depending on if they've completed a challenge or not.

**Comment by LizzHale** [comment]
Hi @jlord -- I would love to get involved with this project and could start by setting up testing infrastructure and writing tests. Do you have any preferences for test frameworks? I've been experimenting with writing some unit tests for the lib modules using jasmine but I'm flexible.

**Comment by jlord** [comment]
@LizzHale HI! 

Getting tests going would be amazing! In general I prefer the lightest weight infrastructure as possible and have used [tap](https://www.npmjs.com/package/tap)/[tape](https://www.npmjs.com/package/tape).

I'm sure that some of my code may need to be restructured—and that's OK, I want it to be better—so that each thing to be tested can be just be required in the test file, run with `tape` and output compared. 

The first, most important things, in my mind, are the verify scripts themselves. This is where the most problems occur. This can also be tricky because many require requests but I'd been thinking it would be nice to have sample data for some of the GitHub requests to use so that tests can still work offline and without needing access to an account.

I'd love to hear your thoughts!

**Comment by LizzHale** [comment]
Thanks for the guidance! I've used TAP implementations for other languages but didn't realize one existed for JavaScript. 
>I'd been thinking it would be nice to have sample data for some of the GitHub requests to use so that tests can still work offline and without needing access to an account.

Agreed! I'll start experimenting and see if I can't come up with something that'll work for the verify scripts.

**Comment by jlord** [comment]
Closing this out because these other things can just be their own issue 🍕
