### ISSUE TITLE
Visual bug: when file path is too long it breaks off

### ISSUE THREAD

**Issue by muan** [jlord/git-it-electron#57]
"select directory" btn and the file path end up on 2 lines and it looks very weird.

**Comment by jlord** [comment]
Yeah, that's why I first moved the _clear_ button to its own line so that the dir could have more space and was hoping people would just have shorter dirs...

I heard you like truncation tho :wink:

**Comment by gamicklisafisher** [comment]
Try using "Long Path Tool", It worked for me.

**Comment by jlord** [comment]
I think this is ok now because the type is smaller than before and if it's long it moves the whole thing to the next line.

<img width="711" alt="screen shot 2016-03-13 at 6 42 00 pm" src="https://cloud.githubusercontent.com/assets/1305617/13733105/5b23c61c-e94b-11e5-9069-ae7ef3e8c77a.png">
