### ISSUE TITLE
Select directory window appears under the git-it-electron window

### ISSUE THREAD

**Issue by IonicaBizau** [jlord/git-it-electron#60]
1. Click <kbd>Select directory</kbd>

   ![image](https://cloud.githubusercontent.com/assets/2864371/9654737/4ea6face-5235-11e5-8d3c-bd927177608d.png)

 2. The *select directory* window appears correctly (on the top).
 3. Click <kbd>Cancel</kbd>
 4. Click again <kbd>Select directory</kbd>

The *select directory* window appears under the git-it-electron window–while I expected to be on the top.

Not sure if this is reproducible on the other platforms. I'm running Ubuntu 15.04. :dizzy:

**Comment by jlord** [comment]
Hmm, yep, I'm seeing it on Ubuntu 14.04. It doesn't happen on OS X or Windows 8.1. There aren't any options on [`dialog.showOpenDialog`](http://electron.atom.io/docs/v0.33.0/api/dialog/#dialog-showopendialog-browserwindow-options-callback) that seem like they'd help. 

Is it an Ubuntu bug or something that should be added in Electron?

**Comment by IonicaBizau** [comment]
@jlord I am almost sure it's an Electron issue–I haven't seen this behavior in other applications. But I will keep an eye on it. Maybe is there any method to *bring such a window on the top* (e.g. *activate* or *focus*)?

**Comment by IonicaBizau** [comment]
@jlord Btw, this does *not* happen in Atom (File -> Open File).

**Comment by IonicaBizau** [comment]
@jlord Ha! The fix was so simple–by simply passing the `mainWindow` object as first argument fixed it. :smile: Addressed in #73.
