### ISSUE TITLE
UX: verifying----- feedfback

### ISSUE THREAD

**Issue by muan** [jlord/git-it-electron#63]
Let user know that we're still working. 

In the challenge "GitHubbin", there are 3 checks, but the second checks uses GitHub API, and for some reasons it hanged (probably internet issues), and it wasn't clear that something "wasn't working", it seemed like the user passed the check(the first one) but the challenge wasn't marked as completed.

More ideal if:

- Spinner?
- Let people know exactly how many checks there are when we start checking, and fill in the result one by one.

**Comment by jlord** [comment]
Yeah, definitely agree :+1:

**Comment by jlord** [comment]
This confetti! Want it http://codepen.io/linrock/pen/Amdhr :tada:
