### ISSUE TITLE
Emoji on Windows and Linux

### ISSUE THREAD

**Issue by jlord** [jlord/git-it-electron#64]
So [this](http://caniemoji.com/windows/) is a bummer:

<img width="791" alt="screen shot 2015-09-03 at 10 47 52 am" src="https://cloud.githubusercontent.com/assets/1305617/9666148/4e782e08-5229-11e5-8721-ea8a59449761.png">

Windows is also not supporting the arrows: ⤷ but it is supporting ☞ ►

Linux is replacing emoji with ☺︎

So, we need a plan, should we keep emoji or replace it? 

cc @muan

**Comment by muan** [comment]
I have some ideas on this specifically related to #63, will probably :fire: emojis here.

**Comment by jlord** [comment]
I think all the emoji are gone now :cry:
