### ISSUE TITLE
Abstract the electron module to be used with other workshops

### ISSUE THREAD

**Issue by azat-co** [jlord/git-it-electron#86]
I would like to use the electron wrapper with other Node School modules like ExpressWorks. Is it possible to abstract/extract the electron-related code into a stand alone module/package? Create some interface?

**Comment by IonicaBizau** [comment]
@azat-co Not a workshop library, but something that abstracts the Electron code a little bit: [`electronify`](https://github.com/IonicaBizau/electronify). Maybe it helps. :smile:

**Comment by azat-co** [comment]
@IonicaBizau NICE, thank you. I've starred it.

**Comment by IonicaBizau** [comment]
@azat-co Thanks!!! :cake:

**Comment by jlord** [comment]
I would like a general Electron based workshop too! I started a repo but but haven't had the :watch: :sweat: I'm going to close here and cross reference there.

**Comment by azat-co** [comment]
@jlord awesomesauce!
