### ISSUE TITLE
Language Content Updates

### ISSUE THREAD

**Issue by jlord** [jlord/git-it-electron#94]
I'm keeping a running list here of text I'm updating in the English version that will need to be updated in the Traditional Chinese and Japanese versions as well. 

I'm going to do a lot of text updates between now and getting Get-it out of beta so **nothing should be updated just yet**. I'll update this thread when the list is complete :sparkles: 

- [x] :eyes: especially on changes to the GitHub UI :computer: 

- https://github.com/jlord/git-it-electron/commit/afa435dabc7c8f961140c38872206dbb745d35d7

**Comment by kohei-takata** [comment]
Hi @jlord !
I want to update Japanese one.
If the list is complete, feel free to tell me!
After that I start updating :smile:

**Comment by jlord** [comment]
Closed via #111
